name: test_unittests

on: [push, pull_request]

jobs:
  test_unittests_success:
    strategy:
      matrix:
        py-version:  ["3.10", 3.11, 3.12]
        np-version:  ["2.0", 2.1, 2.2]
        sp-version:  [1.13, 1.14, 1.15]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up test Python ${{matrix.py-version}}
      uses: actions/setup-python@v5
      with:
        python-version: '~=${{matrix.py-version}}.0'

    - name: Install dependencies (NumPy ${{matrix.np-version}}, SciPy ${{matrix.sp-version}})
      run: |
        pip install numpy~=${{matrix.np-version}}.0
        pip install scipy~=${{matrix.sp-version}}.0
        pip install pandas
        pip install pytest pytest-cov
        pip install --no-deps git+https://github.com/${{ github.repository }}@${{ github.ref_name }}

    - name: Run pytest
      run: |
        pytest --cov-report term-missing --cov=thecannon ./thecannon/tests
