name: test_model_output

on: push

jobs:
  test_model_output_defaults:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up test Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.20'

    - name: Install dependencies
      run: |
        pip install pandas==2.0.3
        pip install numpy==1.22.1
        pip install scipy==1.7.3
        pip install six==1.16.0
        pip install --no-deps git+https://github.com/${{ github.repository }}@${{ github.ref_name }}

    - name: Run run_cannon_andy_svens_python.py
      run: |
        python ./thecannon/tests/actions/run_cannon_andy_svens_python.py

    - name: Check the model is the same as the reference
      uses: LouisBrunner/diff-action@v2.0.0
      with:
        old: thecannon/tests/data/prospect_model_restricted_svens_python.model
        new: thecannon/tests/data/prospect_model_restricted_test.model
        mode: strict
        tolerance: same
        output: model_comparison.txt
